version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: srms_postgres
    restart: always
    ports:
      - "5600:5432"
    environment:
      POSTGRES_USER: srms_user
      POSTGRES_PASSWORD: srms_password
      POSTGRES_DB: srms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: